stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete"

test:
  image: mcr.microsoft.com/playwright
  stage: test
  script:
      - npm ci
      - npx playwright install --with-deps
      - npm run test
